import type { Metadata } from "next";
import { PageHeader } from "@/components/shared/PageHeader";
import { ServiceStats } from "@/components/sections/ServiceStats";
import { ProcessSteps } from "@/components/sections/ProcessSteps";
import { FAQSection } from "@/components/sections/FAQSection";
import { CTASection } from "@/components/sections/CTASection";
import { RelatedServices } from "@/components/sections/RelatedServices";
import { Reveal } from "@/components/shared/Reveal";
import Link from "next/link";

export const metadata: Metadata = {
  title: "LinkedIn Post Assistant — AI B2B Content Generator for US Professionals | HotBot Studios",
  description: "Generate high-engagement LinkedIn posts from blog articles, case studies, and product updates in under 60 seconds. Trained on top-performing B2B content patterns. Maintains your authentic brand voice.",
  keywords: [
    "LinkedIn post automation for founders",
    "B2B thought leadership content tool",
    "AI LinkedIn content strategy",
    "automated LinkedIn posting for executives",
    "LinkedIn content generator for agencies",
    "B2B social media content automation",
    "founder LinkedIn growth tool",
    "AI post writer for LinkedIn USA"
  ],
  openGraph: {
    title: "LinkedIn Post Assistant — AI B2B Content Generator for US Professionals | HotBot Studios",
    description: "Generate high-engagement LinkedIn posts from blog articles, case studies, and product updates in under 60 seconds. Trained on top-performing B2B content patterns. Maintains your authentic brand voice.",
    url: "https://hotbotstudios.com/products/linkedin-post-assistant",
    images: [{ url: "/og-image.svg", width: 1200, height: 630, alt: "LinkedIn Post Assistant: AI-Generated B2B Content That Sounds Like You" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "LinkedIn Post Assistant — AI B2B Content Generator for US Professionals | HotBot Studios",
    description: "Generate high-engagement LinkedIn posts from blog articles, case studies, and product updates in under 60 seconds. Trained on top-performing B2B content patterns. Maintains your authentic brand voice.",
  },
  alternates: { canonical: "https://hotbotstudios.com/products/linkedin-post-assistant" },
};

const productSchema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "LinkedIn Post Assistant: AI-Generated B2B Content That Sounds Like You",
  "description": "Generate high-engagement LinkedIn posts from blog articles, case studies, and product updates in under 60 seconds. Trained on top-performing B2B content patterns. Maintains your authentic brand voice.",
  "applicationCategory": "BusinessApplication",
  "operatingSystem": "Web",
  "offers": {
    "@type": "Offer",
    "price": "0",
    "priceCurrency": "USD",
    "availability": "https://schema.org/OnlineOnly"
  },
  "provider": {
    "@type": "Organization",
    "name": "HotBot Studios",
    "url": "https://hotbotstudios.com"
  },
  "url": "https://hotbotstudios.com/products/linkedin-post-assistant",
  "featureList": "Article-to-Post Conversion, Brand Voice Training, Performance Pattern Learning, Strategic Hashtag Sets, Content Calendar Integration, Repurposing Engine"
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://hotbotstudios.com"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "AI Automation",
      "item": "https://hotbotstudios.com/ai-automation"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "LinkedIn Post Assistant",
      "item": "https://hotbotstudios.com/products/linkedin-post-assistant"
    }
  ]
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "Will posts generated by the assistant sound like AI?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Not if the brand voice onboarding is completed. The assistant is trained on your existing writing samples and calibrates its output to match your sentence length, vocabulary, and preferred post structure. Posts go through a humanization pass that removes common AI patterns before delivery. Most users report that colleagues cannot distinguish assistant-generated posts from manually written ones."
      }
    },
    {
      "@type": "Question",
      "name": "Can I use the assistant for multiple LinkedIn profiles?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes. The assistant supports multiple voice profiles, making it suitable for managing content across executive profiles, a company page, and individual SDR accounts. Each profile maintains its own distinct voice settings and posting history."
      }
    },
    {
      "@type": "Question",
      "name": "Does the assistant post directly to LinkedIn?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "The current version generates posts for your review and exports them to scheduling tools including Buffer, Hootsuite, and LinkedIn's native scheduler. Direct posting via LinkedIn API is available for agency accounts managing multiple profiles."
      }
    },
    {
      "@type": "Question",
      "name": "What types of content work best as input?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Blog articles, case studies, data reports, product announcements, and industry news all generate strong output. The assistant also works from bullet point notes, rough drafts, and topic prompts if you do not have finished content to repurpose. Customer testimonial quotes generate particularly high-engagement story-format posts."
      }
    }
  ]
};

const STATS = [
    { value: 60, suffix: " sec", label: "Post Generation Time", color: "#22c55e" },
    { value: 80, suffix: "%", label: "Reduction in Content Creation Time", color: "#3b82f6" },
    { value: 3, suffix: " variations", label: "Post Options Per Input", color: "#8b5cf6" },
    { value: 5, suffix: "x", label: "Content Output From Single Article Input", color: "#06b6d4" }
];

const PROCESS = [
    { n: 1, title: "Brand Voice Onboarding", desc: "Complete a 10-minute brand voice session: paste 5 to 10 of your best-performing LinkedIn posts or writing samples. The assistant builds your voice profile.", icon: "🎙️" },
    { n: 2, title: "Content Source Setup", desc: "Connect your blog RSS feed, paste article URLs, or upload content directly. The assistant can also work from bullet points or topic prompts.", icon: "📥" },
    { n: 3, title: "Generate and Select", desc: "Generate 3 post variations per input. Review, select, and optionally edit before publishing. Most users publish the first or second variation with minor edits.", icon: "✍️" },
    { n: 4, title: "Schedule and Publish", desc: "Export posts to your scheduling tool or LinkedIn's native scheduler. Run weekly batch sessions to fill your content calendar in under 30 minutes.", icon: "📅" }
];

const FAQS = [
    { q: "Will posts generated by the assistant sound like AI?", a: "Not if the brand voice onboarding is completed. The assistant is trained on your existing writing samples and calibrates its output to match your sentence length, vocabulary, and preferred post structure. Posts go through a humanization pass that removes common AI patterns before delivery. Most users report that colleagues cannot distinguish assistant-generated posts from manually written ones." },
    { q: "Can I use the assistant for multiple LinkedIn profiles?", a: "Yes. The assistant supports multiple voice profiles, making it suitable for managing content across executive profiles, a company page, and individual SDR accounts. Each profile maintains its own distinct voice settings and posting history." },
    { q: "Does the assistant post directly to LinkedIn?", a: "The current version generates posts for your review and exports them to scheduling tools including Buffer, Hootsuite, and LinkedIn's native scheduler. Direct posting via LinkedIn API is available for agency accounts managing multiple profiles." },
    { q: "What types of content work best as input?", a: "Blog articles, case studies, data reports, product announcements, and industry news all generate strong output. The assistant also works from bullet point notes, rough drafts, and topic prompts if you do not have finished content to repurpose. Customer testimonial quotes generate particularly high-engagement story-format posts." }
];

const RELATED = [
    { title: "Instagram Content Assistant", href: "/products/instagram-content-assistant", desc: "AI-generated captions, hooks, and hashtag sets for Instagram Reels, Stories, and Feed posts.", icon: "📸" },
    { title: "Content Production Studio", href: "/content-studio", desc: "Full content production: video, copy, social media, and podcast production for US brands.", icon: "🎬" },
    { title: "Social Media Marketing", href: "/marketing-services/social-media", desc: "Managed LinkedIn, Instagram, and multi-platform social media strategy and content.", icon: "📣" }
];

export default function LinkedinPostAssistantPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* Breadcrumb */}
      <nav className="pt-24 pb-0 px-6 max-w-5xl mx-auto">
        <ol className="flex items-center gap-2 text-xs text-slate-500">
          <li><Link href="/" className="hover:text-slate-300 transition-colors">Home</Link></li>
          <li className="text-slate-700">/</li>
          <li><Link href="/ai-automation" className="hover:text-slate-300 transition-colors">AI Automation</Link></li>
          <li className="text-slate-700">/</li>
          <li className="text-slate-400">LinkedIn Post Assistant</li>
        </ol>
      </nav>

      <PageHeader
        label="LinkedIn Content Automation"
        title="LinkedIn Post Assistant: AI-Generated B2B Content That Sounds Like You"
        subtitle="Your LinkedIn presence is a lead generation asset that most B2B companies underuse because consistent content creation takes too long. The LinkedIn Post Assistant generates scroll-stopping posts from your existing blog articles, product updates, case studies, and industry news. Trained on performance data from high-engaging B2B content patterns. Maintains your authentic voice while reducing content creation time from hours to under 60 seconds per post."
      />

      {/* AEO Definition Block */}
      <Reveal>
        <section className="relative z-10 py-8 px-6 max-w-3xl mx-auto">
          <div
            className="p-6 rounded-2xl border"
            style={{ background: "rgba(59,130,246,0.04)", borderColor: "rgba(59,130,246,0.15)" }}
          >
            <p className="text-slate-300 text-sm leading-relaxed">
              <strong className="text-white">LinkedIn Post Assistant:</strong>{" "}
              The LinkedIn Post Assistant is an AI content generation tool that converts B2B inputs including blog posts, news articles, product announcements, and case studies into high-engagement LinkedIn posts. Trained on performance data from top-performing B2B LinkedIn content, it applies pattern recognition to match your brand voice while optimizing output for reach, engagement, and profile authority growth on the LinkedIn platform.
            </p>
          </div>
        </section>
      </Reveal>

      {/* Stats */}
      <ServiceStats stats={STATS} title="By the Numbers" />

      {/* Features Grid */}
      <section className="relative z-10 py-16 px-6 max-w-5xl mx-auto">
        <Reveal>
          <h2 className="text-2xl md:text-3xl font-bold text-white text-center mb-10">Core Capabilities</h2>
        </Reveal>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        <div key="Article-to-Post Conversion" className="p-5 rounded-2xl border" style={{ background: "#22c55e10", borderColor: "#22c55e25" }}>
          <div className="text-2xl mb-3">{String.raw`✍️`}</div>
          <h3 className="font-semibold text-white text-sm mb-2">{String.raw`Article-to-Post Conversion`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed">{String.raw`Paste any blog URL or article text and receive 3 LinkedIn post variations in under 60 seconds. Each variation uses a different hook format: data-led, story-driven, or contrarian. Choose the version that fits your voice.`}</p>
        </div>
        <div key="Brand Voice Training" className="p-5 rounded-2xl border" style={{ background: "#3b82f610", borderColor: "#3b82f625" }}>
          <div className="text-2xl mb-3">{String.raw`🎙️`}</div>
          <h3 className="font-semibold text-white text-sm mb-2">{String.raw`Brand Voice Training`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed">{String.raw`Complete a one-time 10-minute brand voice session. The assistant learns your preferred language, tone, and sentence structure. Posts consistently sound like you, not like generic AI output.`}</p>
        </div>
        <div key="Performance Pattern Learning" className="p-5 rounded-2xl border" style={{ background: "#8b5cf610", borderColor: "#8b5cf625" }}>
          <div className="text-2xl mb-3">{String.raw`📊`}</div>
          <h3 className="font-semibold text-white text-sm mb-2">{String.raw`Performance Pattern Learning`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed">{String.raw`The assistant analyzes engagement patterns across your previous posts and the highest-performing content in your industry. Over time, it weights its output toward the formats, lengths, and hook structures that drive results for your specific audience.`}</p>
        </div>
        <div key="Strategic Hashtag Sets" className="p-5 rounded-2xl border" style={{ background: "#06b6d410", borderColor: "#06b6d425" }}>
          <div className="text-2xl mb-3">{String.raw`🏷️`}</div>
          <h3 className="font-semibold text-white text-sm mb-2">{String.raw`Strategic Hashtag Sets`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed">{String.raw`Generates categorized hashtag sets for each post: 3 broad industry tags, 3 niche community tags, and 2 trending tags based on current LinkedIn algorithm signals. No guesswork on hashtag strategy.`}</p>
        </div>
        <div key="Content Calendar Integration" className="p-5 rounded-2xl border" style={{ background: "#f59e0b10", borderColor: "#f59e0b25" }}>
          <div className="text-2xl mb-3">{String.raw`📅`}</div>
          <h3 className="font-semibold text-white text-sm mb-2">{String.raw`Content Calendar Integration`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed">{String.raw`Export posts directly to Buffer, Hootsuite, or LinkedIn's native scheduler. Schedule a full week of content in under 30 minutes from a single batch generation session.`}</p>
        </div>
        <div key="Repurposing Engine" className="p-5 rounded-2xl border" style={{ background: "#ec489910", borderColor: "#ec489925" }}>
          <div className="text-2xl mb-3">{String.raw`🔁`}</div>
          <h3 className="font-semibold text-white text-sm mb-2">{String.raw`Repurposing Engine`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed">{String.raw`Upload a single long-form piece and receive 5 derivative post formats: a data stat post, a listicle, a personal story angle, a question post for comments, and a contrarian take. Extends the value of every content investment.`}</p>
        </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="relative z-10 py-16 px-6 max-w-5xl mx-auto">
        <Reveal>
          <h2 className="text-2xl md:text-3xl font-bold text-white text-center mb-10">Industry Use Cases</h2>
        </Reveal>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div key="B2B Founders and CEOs" className="p-6 rounded-2xl border" style={{ background: "#22c55e08", borderColor: "#22c55e20" }}>
          <h3 className="font-semibold mb-2" style={{ color: "#22c55e" }}>{String.raw`B2B Founders and CEOs`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed mb-3"><strong className="text-slate-300">Challenge:</strong> {String.raw`Need consistent LinkedIn presence for lead generation and investor visibility but do not have time to write posts regularly.`}</p>
          <p className="text-slate-400 text-xs leading-relaxed"><strong className="text-slate-300">Solution:</strong> {String.raw`Generate a week of posts in 15 minutes from existing blog content and business updates. Maintain a daily posting cadence without writing a single word manually.`}</p>
        </div>
        <div key="B2B Marketing Teams" className="p-6 rounded-2xl border" style={{ background: "#3b82f608", borderColor: "#3b82f620" }}>
          <h3 className="font-semibold mb-2" style={{ color: "#3b82f6" }}>{String.raw`B2B Marketing Teams`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed mb-3"><strong className="text-slate-300">Challenge:</strong> {String.raw`Content calendar requires 5 to 7 LinkedIn posts per week across executive and brand profiles. Writing is the bottleneck.`}</p>
          <p className="text-slate-400 text-xs leading-relaxed"><strong className="text-slate-300">Solution:</strong> {String.raw`Batch generate posts for all profiles from a single content input session. Maintain distinct voice profiles for each executive. Reduce content writing time by 80 percent.`}</p>
        </div>
        <div key="Sales Development Representatives" className="p-6 rounded-2xl border" style={{ background: "#8b5cf608", borderColor: "#8b5cf620" }}>
          <h3 className="font-semibold mb-2" style={{ color: "#8b5cf6" }}>{String.raw`Sales Development Representatives`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed mb-3"><strong className="text-slate-300">Challenge:</strong> {String.raw`Personal branding on LinkedIn drives inbound leads but most SDRs do not post consistently because writing takes too long.`}</p>
          <p className="text-slate-400 text-xs leading-relaxed"><strong className="text-slate-300">Solution:</strong> {String.raw`SDRs generate posts from company blog content, industry news, and deal insights in under 60 seconds. Consistent personal posting with minimal time investment.`}</p>
        </div>
        <div key="Marketing Agencies" className="p-6 rounded-2xl border" style={{ background: "#06b6d408", borderColor: "#06b6d420" }}>
          <h3 className="font-semibold mb-2" style={{ color: "#06b6d4" }}>{String.raw`Marketing Agencies`}</h3>
          <p className="text-slate-400 text-xs leading-relaxed mb-3"><strong className="text-slate-300">Challenge:</strong> {String.raw`Managing LinkedIn content for 10 to 20 B2B clients requires significant writing time each week.`}</p>
          <p className="text-slate-400 text-xs leading-relaxed"><strong className="text-slate-300">Solution:</strong> {String.raw`Batch generate posts for all client profiles using their blog feeds and brand voice profiles. Reduce per-client content creation time from 3 hours to under 30 minutes per week.`}</p>
        </div>
        </div>
      </section>

      {/* Process */}
      <ProcessSteps steps={PROCESS} title="How We Deploy" />

      {/* KPIs */}
      <Reveal>
        <section className="relative z-10 py-16 px-6 max-w-3xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold text-white text-center mb-8">KPIs We Track</h2>
          <div
            className="p-8 rounded-2xl border"
            style={{ background: "rgba(139,92,246,0.04)", borderColor: "rgba(139,92,246,0.15)" }}
          >
            <ul className="space-y-3 list-none">
          <li className="text-slate-300 text-sm">{String.raw`Posts published per week (target: 5 or more)`}</li>
          <li className="text-slate-300 text-sm">{String.raw`Average post impressions over 30-day rolling average`}</li>
          <li className="text-slate-300 text-sm">{String.raw`Engagement rate per post (target: 2 percent or above)`}</li>
          <li className="text-slate-300 text-sm">{String.raw`Profile page views per month`}</li>
          <li className="text-slate-300 text-sm">{String.raw`Connection requests received from target ICP accounts`}</li>
          <li className="text-slate-300 text-sm">{String.raw`Inbound leads attributed to LinkedIn content per quarter`}</li>
            </ul>
          </div>
        </section>
      </Reveal>

      {/* FAQ */}
      <FAQSection faqs={FAQS} />

      {/* Key Takeaways */}
      <Reveal>
        <section className="relative z-10 py-16 px-6 max-w-3xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold text-white text-center mb-8">Key Takeaways</h2>
          <ul className="space-y-4">
          <li className="flex items-start gap-2 text-slate-300 text-sm">
            <span className="text-green-400 mt-0.5 flex-shrink-0">✓</span>
            <span>{String.raw`Generates 3 LinkedIn post variations from any blog article or content input in under 60 seconds`}</span>
          </li>
          <li className="flex items-start gap-2 text-slate-300 text-sm">
            <span className="text-green-400 mt-0.5 flex-shrink-0">✓</span>
            <span>{String.raw`Brand voice training ensures posts sound like you, not generic AI output`}</span>
          </li>
          <li className="flex items-start gap-2 text-slate-300 text-sm">
            <span className="text-green-400 mt-0.5 flex-shrink-0">✓</span>
            <span>{String.raw`Repurposing engine extracts 5 different post formats from a single content piece`}</span>
          </li>
          <li className="flex items-start gap-2 text-slate-300 text-sm">
            <span className="text-green-400 mt-0.5 flex-shrink-0">✓</span>
            <span>{String.raw`Strategic hashtag sets include broad industry, niche community, and trending tags per post`}</span>
          </li>
          <li className="flex items-start gap-2 text-slate-300 text-sm">
            <span className="text-green-400 mt-0.5 flex-shrink-0">✓</span>
            <span>{String.raw`Exports directly to Buffer, Hootsuite, and LinkedIn native scheduler for batch scheduling`}</span>
          </li>
          <li className="flex items-start gap-2 text-slate-300 text-sm">
            <span className="text-green-400 mt-0.5 flex-shrink-0">✓</span>
            <span>{String.raw`Supports multiple voice profiles for agencies managing content across executive and brand accounts`}</span>
          </li>
          </ul>
        </section>
      </Reveal>

      {/* Related Services */}
      <RelatedServices services={RELATED} />

      {/* CTA */}
      <CTASection
        title="Generate Your First LinkedIn Post in 60 Seconds"
        subtitle="Paste any blog article URL and receive 3 post variations calibrated to your brand voice. No credit card required for your first 5 posts."
        formType="get-started"
      />
    </>
  );
}
